### ISSUE TITLE
Decide on structure and stubs for new website

### ISSUE THREAD

**Issue by dcnb** [lib-static/lib-static.github.io#2]
First suggested template: 

https://github.com/lib-static/lib-static.github.io/blob/new_site/_projects/template.md

Need to decide if Code is a separate thing. If this makes sense. 

I am thinking it's got a lot right with it right now ...

**Comment by evanwill** [comment]
- i don't think you need objectid, objecttype. The objectid can just be the `page.name`. objecttype is based on which collection it is in, so you have that already too. 
- i think switch `github-repo` to something platform neutral, since might be gitlab, bitbucket, or what ever. `code-repo` or `repository`?
- i think some space or comment lines between the keys would make it easier to read, gets really confusing around people and images. the lists are hard to tell apart. 
- people might just want to use "link" rather than github to be neutral. could be a home page, github, twitter, what ever people want to use.
- images `filelocation` seems odd key, just use `src`, `alt`, and `caption` to keep with normal conventions. imgs need alt.

I wonder if rather than writing it all as yml front matter, there could just be a template content in the file too, so you could write up your description there in markdown however you wanted. 

Might be helpful to highlight the `>` option in yml. e.g. 

```
description: > 
  writing a big description. 
  all this counts as part of the same value if indented, and
  until there is a new key.
category: Library Website
```

Combine that with `markdownify` filter so that you can use markdown in the values, e.g. `{{ page.description | markdownify }}`
